STEP_PIN = 4
DIR_PIN = 18
ENABLE_PIN = None

STEPS_REV = 200
MICROSTEPS = 16 # 1 if none
INVERT_DIR = False
GEARBOX_MODIFIER = 3
MICROSTEPS_REV = STEPS_REV * MICROSTEPS
SPEED_SPS = MICROSTEPS_REV / 2

WIFI_TIMEOUT_SECONDS = 20

BUTTON_PIN = 7
BUTTON_DEBOUNCE_MS = 200
