# motor
STEP_PIN = 12
DIR_PIN = 14
ENABLE_PIN = None

STEPS_REV = 200
MICROSTEPS = 16  # 1 if none
INVERT_DIR = False
GEARBOX_MODIFIER = 3
MICROSTEPS_REV = STEPS_REV * MICROSTEPS
SPEED_SPS = MICROSTEPS_REV / 2

# button
BUTTON_PIN = 13
BUTTON_DEBOUNCE_MS = 200

# network
WIFI_TIMEOUT_SECONDS = 20

# dmx
DMX_DRIVE_SEND_PIN = 18
DMX_SEND_ENABLE_PIN = 17  # active high
DMX_DRIVE_RECEIVE_PIN = 15
DMX_RECEIVE_ENABLE_PIN = 16  # active low
